# TCL File Generated by Component Editor 23.1
# Tue Jul 01 22:35:58 SGT 2025
# DO NOT MODIFY


# 
# adc_fifo_reader "adc_fifo_reader" v1.0
# Dennis Wong Guan Ming 2025.07.01.22:35:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module adc_fifo_reader
# 
set_module_property DESCRIPTION ""
set_module_property NAME adc_fifo_reader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Dennis Wong Guan Ming"
set_module_property DISPLAY_NAME adc_fifo_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL adc_fifo_reader_mm_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file adc_fifo_reader_mm_slave.v VERILOG PATH adc_fifo_reader_mm_slave.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point adc_fifo_reader_avalon_slave
# 
add_interface adc_fifo_reader_avalon_slave avalon end
set_interface_property adc_fifo_reader_avalon_slave addressUnits WORDS
set_interface_property adc_fifo_reader_avalon_slave associatedClock clock
set_interface_property adc_fifo_reader_avalon_slave associatedReset reset
set_interface_property adc_fifo_reader_avalon_slave bitsPerSymbol 8
set_interface_property adc_fifo_reader_avalon_slave burstOnBurstBoundariesOnly false
set_interface_property adc_fifo_reader_avalon_slave burstcountUnits WORDS
set_interface_property adc_fifo_reader_avalon_slave explicitAddressSpan 0
set_interface_property adc_fifo_reader_avalon_slave holdTime 0
set_interface_property adc_fifo_reader_avalon_slave linewrapBursts false
set_interface_property adc_fifo_reader_avalon_slave maximumPendingReadTransactions 0
set_interface_property adc_fifo_reader_avalon_slave maximumPendingWriteTransactions 0
set_interface_property adc_fifo_reader_avalon_slave readLatency 0
set_interface_property adc_fifo_reader_avalon_slave readWaitTime 1
set_interface_property adc_fifo_reader_avalon_slave setupTime 0
set_interface_property adc_fifo_reader_avalon_slave timingUnits Cycles
set_interface_property adc_fifo_reader_avalon_slave writeWaitTime 0
set_interface_property adc_fifo_reader_avalon_slave ENABLED true
set_interface_property adc_fifo_reader_avalon_slave EXPORT_OF ""
set_interface_property adc_fifo_reader_avalon_slave PORT_NAME_MAP ""
set_interface_property adc_fifo_reader_avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property adc_fifo_reader_avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port adc_fifo_reader_avalon_slave address address Input 2
add_interface_port adc_fifo_reader_avalon_slave read read Input 1
add_interface_port adc_fifo_reader_avalon_slave readdata readdata Output 128
add_interface_port adc_fifo_reader_avalon_slave waitrequest waitrequest Output 1
set_interface_assignment adc_fifo_reader_avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment adc_fifo_reader_avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment adc_fifo_reader_avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment adc_fifo_reader_avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point adc_fifo_reader_conduit
# 
add_interface adc_fifo_reader_conduit conduit end
set_interface_property adc_fifo_reader_conduit associatedClock clock
set_interface_property adc_fifo_reader_conduit associatedReset reset
set_interface_property adc_fifo_reader_conduit ENABLED true
set_interface_property adc_fifo_reader_conduit EXPORT_OF ""
set_interface_property adc_fifo_reader_conduit PORT_NAME_MAP ""
set_interface_property adc_fifo_reader_conduit CMSIS_SVD_VARIABLES ""
set_interface_property adc_fifo_reader_conduit SVD_ADDRESS_GROUP ""

add_interface_port adc_fifo_reader_conduit fifo_data_in fifo_data_in Input 128
add_interface_port adc_fifo_reader_conduit fifo_empty fifo_empty Input 1
add_interface_port adc_fifo_reader_conduit fifo_rdreq fifo_rdreq Output 1

